services:
  postgres:
    image: postgres:17
    container_name: nextrep-pg
    env_file: .env
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgres/data

  frontend:
    build:
      context: ./packages/frontend/
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '5173:3000'

  backend:
    build:
      context: ./packages/backend/
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '${PORT}:${PORT}'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres

volumes:
  pg_data:
    driver: local
