services:
  postgres:
    image: postgres:17
    container_name: nextrep-pg-dev
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pg_data_dev:/var/lib/postgres/data

volumes:
  pg_data_dev:
    driver: local

