services:
  postgres:
    image: postgres:17
    container_name: nextrep-pg
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgres/data

volumes:
  pg_data:
    driver: local
