services:
  postgres:
    image: postgres:17
    container_name: nextrep-pg
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgres/data

  # frontend:
  #   build:
  #     context: ./packages/frontend
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./packages/frontend/.env
  #   ports:
  #     - '5173:5173'

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    env_file:
      - ./packages/backend/.env
    ports:
      - '${PORT}:3000'
    environment:
      - HOST=0.0.0.0
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres

volumes:
  pg_data:
    driver: local
