services:
  postgres:
    image: postgres:17
    container_name: nextrep-pg
    env_file: .env.docker
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgres/data

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    env_file: .env.docker
    ports:
      - 5173:5173

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    env_file: .env.docker
    ports:
      - 3000:3000
    depends_on:
      - postgres

volumes:
  pg_data:
    driver: local
